###
POST http://localhost:8080/region/created
Content-Type: application/json

{
  "orderNumber": "1",
  "nameUz": "uu",
  "nameEng": "ee",
  "nameRu": "rr"
}


###
PUT http://localhost:8080/region/update/3
Content-Type: application/json

{
  "orderNumber": "O1",
  "nameUz": "UU1",
  "nameEng": "EE1",
  "nameRu": "RR1"
}


###
DELETE http://localhost:8080/region/deleted/3


###
GET http://localhost:8080/region/getByList?size=2&page=1


###
GET http://localhost:8080/region/getByLang?language=uz
Accept-Language: uz


